//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SgkIseGirisServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr", ConfigurationName="SgkIseGirisServiceReference.WS_SgkIseGiris")]
    public interface WS_SgkIseGiris
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="iseGirisKaydet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SgkIseGirisServiceReference.iseGirisKaydetResponse> iseGirisKaydetAsync(SgkIseGirisServiceReference.iseGirisKaydetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="iseGirisPdfDokum", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SgkIseGirisServiceReference.iseGirisPdfDokumResponse> iseGirisPdfDokumAsync(SgkIseGirisServiceReference.iseGirisPdfDokumRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="tckimlikNoileiseGirisSorgula", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SgkIseGirisServiceReference.tckimlikNoileiseGirisSorgulaResponse> tckimlikNoileiseGirisSorgulaAsync(SgkIseGirisServiceReference.tckimlikNoileiseGirisSorgulaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="tckimlikNoTarihileiseGirisSorgula", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SgkIseGirisServiceReference.tckimlikNoTarihileiseGirisSorgulaResponse> tckimlikNoTarihileiseGirisSorgulaAsync(SgkIseGirisServiceReference.tckimlikNoTarihileiseGirisSorgulaRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr")]
    public partial class sgk4AIseGirisParametre
    {
        
        private kullaniciBilgileri kullaniciBilgileriField;
        
        private sigortaliIseGiris[] sigortaliIseGirisListesiField;
        
        private string ayniIsverenFarkliIsyeriNakilField;
        
        private string nakilGeldigiIsyeriSicilField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public kullaniciBilgileri kullaniciBilgileri
        {
            get
            {
                return this.kullaniciBilgileriField;
            }
            set
            {
                this.kullaniciBilgileriField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sigortaliIseGirisListesi", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public sigortaliIseGiris[] sigortaliIseGirisListesi
        {
            get
            {
                return this.sigortaliIseGirisListesiField;
            }
            set
            {
                this.sigortaliIseGirisListesiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ayniIsverenFarkliIsyeriNakil
        {
            get
            {
                return this.ayniIsverenFarkliIsyeriNakilField;
            }
            set
            {
                this.ayniIsverenFarkliIsyeriNakilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nakilGeldigiIsyeriSicil
        {
            get
            {
                return this.nakilGeldigiIsyeriSicilField;
            }
            set
            {
                this.nakilGeldigiIsyeriSicilField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr")]
    public partial class kullaniciBilgileri
    {
        
        private string kullaniciAdiField;
        
        private string isyeriKoduField;
        
        private string sistemSifreField;
        
        private string isyeriSifreField;
        
        private string isyeriSicilField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string kullaniciAdi
        {
            get
            {
                return this.kullaniciAdiField;
            }
            set
            {
                this.kullaniciAdiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string isyeriKodu
        {
            get
            {
                return this.isyeriKoduField;
            }
            set
            {
                this.isyeriKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string sistemSifre
        {
            get
            {
                return this.sistemSifreField;
            }
            set
            {
                this.sistemSifreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string isyeriSifre
        {
            get
            {
                return this.isyeriSifreField;
            }
            set
            {
                this.isyeriSifreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string isyeriSicil
        {
            get
            {
                return this.isyeriSicilField;
            }
            set
            {
                this.isyeriSicilField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr")]
    public partial class tcKimlikTarihtenIseGirisSorParametre
    {
        
        private kullaniciBilgileri kullaniciBilgileriField;
        
        private long tcKimlikNoField;
        
        private string iseGirisTarihiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public kullaniciBilgileri kullaniciBilgileri
        {
            get
            {
                return this.kullaniciBilgileriField;
            }
            set
            {
                this.kullaniciBilgileriField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long tcKimlikNo
        {
            get
            {
                return this.tcKimlikNoField;
            }
            set
            {
                this.tcKimlikNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string iseGirisTarihi
        {
            get
            {
                return this.iseGirisTarihiField;
            }
            set
            {
                this.iseGirisTarihiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr")]
    public partial class sgkIseGirisKaydi
    {
        
        private long tckimlikNoField;
        
        private long sicilnoField;
        
        private string girisTarihiField;
        
        private string sigortaTuruField;
        
        private string istisnaKoduField;
        
        private string islemTarihiField;
        
        private double idariParaCezasiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long tckimlikNo
        {
            get
            {
                return this.tckimlikNoField;
            }
            set
            {
                this.tckimlikNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long sicilno
        {
            get
            {
                return this.sicilnoField;
            }
            set
            {
                this.sicilnoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string girisTarihi
        {
            get
            {
                return this.girisTarihiField;
            }
            set
            {
                this.girisTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string sigortaTuru
        {
            get
            {
                return this.sigortaTuruField;
            }
            set
            {
                this.sigortaTuruField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string istisnaKodu
        {
            get
            {
                return this.istisnaKoduField;
            }
            set
            {
                this.istisnaKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string islemTarihi
        {
            get
            {
                return this.islemTarihiField;
            }
            set
            {
                this.islemTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public double idariParaCezasi
        {
            get
            {
                return this.idariParaCezasiField;
            }
            set
            {
                this.idariParaCezasiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr")]
    public partial class iseGirisListesi
    {
        
        private int hatakoduField;
        
        private string hataAciklamaField;
        
        private sgkIseGirisKaydi[] iseGirisKayitlariField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int hatakodu
        {
            get
            {
                return this.hatakoduField;
            }
            set
            {
                this.hatakoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string hataAciklama
        {
            get
            {
                return this.hataAciklamaField;
            }
            set
            {
                this.hataAciklamaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("iseGirisKayitlari", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public sgkIseGirisKaydi[] iseGirisKayitlari
        {
            get
            {
                return this.iseGirisKayitlariField;
            }
            set
            {
                this.iseGirisKayitlariField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr")]
    public partial class tcKimliktenIseGirisSorParametre
    {
        
        private kullaniciBilgileri kullaniciBilgileriField;
        
        private long tcKimlikNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public kullaniciBilgileri kullaniciBilgileri
        {
            get
            {
                return this.kullaniciBilgileriField;
            }
            set
            {
                this.kullaniciBilgileriField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long tcKimlikNo
        {
            get
            {
                return this.tcKimlikNoField;
            }
            set
            {
                this.tcKimlikNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr")]
    public partial class pdfDokumSonuc
    {
        
        private string hataAciklamaField;
        
        private int hatakoduField;
        
        private byte[] pdfByteArrayField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string hataAciklama
        {
            get
            {
                return this.hataAciklamaField;
            }
            set
            {
                this.hataAciklamaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int hatakodu
        {
            get
            {
                return this.hatakoduField;
            }
            set
            {
                this.hatakoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=2)]
        public byte[] pdfByteArray
        {
            get
            {
                return this.pdfByteArrayField;
            }
            set
            {
                this.pdfByteArrayField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr")]
    public partial class sigortaliIseGirisSonuc
    {
        
        private long islemSonucuField;
        
        private string islemAciklamasiField;
        
        private long tcKimlikNoField;
        
        private long sicilnoField;
        
        private string adSoyadField;
        
        private long referansKoduField;
        
        private string iseGirisTarihiField;
        
        private string isyeriSicilField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long islemSonucu
        {
            get
            {
                return this.islemSonucuField;
            }
            set
            {
                this.islemSonucuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string islemAciklamasi
        {
            get
            {
                return this.islemAciklamasiField;
            }
            set
            {
                this.islemAciklamasiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long tcKimlikNo
        {
            get
            {
                return this.tcKimlikNoField;
            }
            set
            {
                this.tcKimlikNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public long sicilno
        {
            get
            {
                return this.sicilnoField;
            }
            set
            {
                this.sicilnoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string adSoyad
        {
            get
            {
                return this.adSoyadField;
            }
            set
            {
                this.adSoyadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public long referansKodu
        {
            get
            {
                return this.referansKoduField;
            }
            set
            {
                this.referansKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string iseGirisTarihi
        {
            get
            {
                return this.iseGirisTarihiField;
            }
            set
            {
                this.iseGirisTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string isyeriSicil
        {
            get
            {
                return this.isyeriSicilField;
            }
            set
            {
                this.isyeriSicilField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr")]
    public partial class sigortaliIseGirisIslemSonuclari
    {
        
        private int hataKoduField;
        
        private string hataAciklamasiField;
        
        private sigortaliIseGirisSonuc[] sigortaliIseGirisSonucField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int hataKodu
        {
            get
            {
                return this.hataKoduField;
            }
            set
            {
                this.hataKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string hataAciklamasi
        {
            get
            {
                return this.hataAciklamasiField;
            }
            set
            {
                this.hataAciklamasiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sigortaliIseGirisSonuc", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public sigortaliIseGirisSonuc[] sigortaliIseGirisSonuc
        {
            get
            {
                return this.sigortaliIseGirisSonucField;
            }
            set
            {
                this.sigortaliIseGirisSonucField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr")]
    public partial class sigortaliIseGiris
    {
        
        private long tckimlikNoField;
        
        private string adField;
        
        private string soyadField;
        
        private string giristarihiField;
        
        private short sigortaliTuruField;
        
        private string gorevkoduField;
        
        private string meslekkoduField;
        
        private string csgbiskoluField;
        
        private string eskihukumluField;
        
        private string ozurluField;
        
        private string ogrenimkoduField;
        
        private string mezuniyetbolumuField;
        
        private short mezuniyetyiliField;
        
        private string kismiSureliCalisiyormuField;
        
        private short kismiSureliCalismaGunSayisiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long tckimlikNo
        {
            get
            {
                return this.tckimlikNoField;
            }
            set
            {
                this.tckimlikNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ad
        {
            get
            {
                return this.adField;
            }
            set
            {
                this.adField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string soyad
        {
            get
            {
                return this.soyadField;
            }
            set
            {
                this.soyadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string giristarihi
        {
            get
            {
                return this.giristarihiField;
            }
            set
            {
                this.giristarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public short sigortaliTuru
        {
            get
            {
                return this.sigortaliTuruField;
            }
            set
            {
                this.sigortaliTuruField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string gorevkodu
        {
            get
            {
                return this.gorevkoduField;
            }
            set
            {
                this.gorevkoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string meslekkodu
        {
            get
            {
                return this.meslekkoduField;
            }
            set
            {
                this.meslekkoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string csgbiskolu
        {
            get
            {
                return this.csgbiskoluField;
            }
            set
            {
                this.csgbiskoluField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string eskihukumlu
        {
            get
            {
                return this.eskihukumluField;
            }
            set
            {
                this.eskihukumluField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string ozurlu
        {
            get
            {
                return this.ozurluField;
            }
            set
            {
                this.ozurluField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string ogrenimkodu
        {
            get
            {
                return this.ogrenimkoduField;
            }
            set
            {
                this.ogrenimkoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string mezuniyetbolumu
        {
            get
            {
                return this.mezuniyetbolumuField;
            }
            set
            {
                this.mezuniyetbolumuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public short mezuniyetyili
        {
            get
            {
                return this.mezuniyetyiliField;
            }
            set
            {
                this.mezuniyetyiliField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string kismiSureliCalisiyormu
        {
            get
            {
                return this.kismiSureliCalisiyormuField;
            }
            set
            {
                this.kismiSureliCalisiyormuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public short kismiSureliCalismaGunSayisi
        {
            get
            {
                return this.kismiSureliCalismaGunSayisiField;
            }
            set
            {
                this.kismiSureliCalismaGunSayisiField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="iseGirisKaydet", WrapperNamespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr", IsWrapped=true)]
    public partial class iseGirisKaydetRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SgkIseGirisServiceReference.sgk4AIseGirisParametre sgk4aIseGirisParametre;
        
        public iseGirisKaydetRequest()
        {
        }
        
        public iseGirisKaydetRequest(SgkIseGirisServiceReference.sgk4AIseGirisParametre sgk4aIseGirisParametre)
        {
            this.sgk4aIseGirisParametre = sgk4aIseGirisParametre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="iseGirisKaydetResponse", WrapperNamespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr", IsWrapped=true)]
    public partial class iseGirisKaydetResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SgkIseGirisServiceReference.sigortaliIseGirisIslemSonuclari iseGirisKaydetReturn;
        
        public iseGirisKaydetResponse()
        {
        }
        
        public iseGirisKaydetResponse(SgkIseGirisServiceReference.sigortaliIseGirisIslemSonuclari iseGirisKaydetReturn)
        {
            this.iseGirisKaydetReturn = iseGirisKaydetReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="iseGirisPdfDokum", WrapperNamespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr", IsWrapped=true)]
    public partial class iseGirisPdfDokumRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SgkIseGirisServiceReference.kullaniciBilgileri kullanici;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long referansKodu;
        
        public iseGirisPdfDokumRequest()
        {
        }
        
        public iseGirisPdfDokumRequest(SgkIseGirisServiceReference.kullaniciBilgileri kullanici, long referansKodu)
        {
            this.kullanici = kullanici;
            this.referansKodu = referansKodu;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="iseGirisPdfDokumResponse", WrapperNamespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr", IsWrapped=true)]
    public partial class iseGirisPdfDokumResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SgkIseGirisServiceReference.pdfDokumSonuc iseGirisPdfDokumReturn;
        
        public iseGirisPdfDokumResponse()
        {
        }
        
        public iseGirisPdfDokumResponse(SgkIseGirisServiceReference.pdfDokumSonuc iseGirisPdfDokumReturn)
        {
            this.iseGirisPdfDokumReturn = iseGirisPdfDokumReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="tckimlikNoileiseGirisSorgula", WrapperNamespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr", IsWrapped=true)]
    public partial class tckimlikNoileiseGirisSorgulaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SgkIseGirisServiceReference.tcKimliktenIseGirisSorParametre tcKimliktenIseGirisSorParametre;
        
        public tckimlikNoileiseGirisSorgulaRequest()
        {
        }
        
        public tckimlikNoileiseGirisSorgulaRequest(SgkIseGirisServiceReference.tcKimliktenIseGirisSorParametre tcKimliktenIseGirisSorParametre)
        {
            this.tcKimliktenIseGirisSorParametre = tcKimliktenIseGirisSorParametre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="tckimlikNoileiseGirisSorgulaResponse", WrapperNamespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr", IsWrapped=true)]
    public partial class tckimlikNoileiseGirisSorgulaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SgkIseGirisServiceReference.iseGirisListesi tckimlikNoileiseGirisSorgulaReturn;
        
        public tckimlikNoileiseGirisSorgulaResponse()
        {
        }
        
        public tckimlikNoileiseGirisSorgulaResponse(SgkIseGirisServiceReference.iseGirisListesi tckimlikNoileiseGirisSorgulaReturn)
        {
            this.tckimlikNoileiseGirisSorgulaReturn = tckimlikNoileiseGirisSorgulaReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="tckimlikNoTarihileiseGirisSorgula", WrapperNamespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr", IsWrapped=true)]
    public partial class tckimlikNoTarihileiseGirisSorgulaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SgkIseGirisServiceReference.tcKimlikTarihtenIseGirisSorParametre tcKimlikTarihtenIseGirisSorParametre;
        
        public tckimlikNoTarihileiseGirisSorgulaRequest()
        {
        }
        
        public tckimlikNoTarihileiseGirisSorgulaRequest(SgkIseGirisServiceReference.tcKimlikTarihtenIseGirisSorParametre tcKimlikTarihtenIseGirisSorParametre)
        {
            this.tcKimlikTarihtenIseGirisSorParametre = tcKimlikTarihtenIseGirisSorParametre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="tckimlikNoTarihileiseGirisSorgulaResponse", WrapperNamespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr", IsWrapped=true)]
    public partial class tckimlikNoTarihileiseGirisSorgulaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SgkIseGirisServiceReference.iseGirisListesi tckimlikNoTarihileiseGirisSorgulaReturn;
        
        public tckimlikNoTarihileiseGirisSorgulaResponse()
        {
        }
        
        public tckimlikNoTarihileiseGirisSorgulaResponse(SgkIseGirisServiceReference.iseGirisListesi tckimlikNoTarihileiseGirisSorgulaReturn)
        {
            this.tckimlikNoTarihileiseGirisSorgulaReturn = tckimlikNoTarihileiseGirisSorgulaReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface WS_SgkIseGirisChannel : SgkIseGirisServiceReference.WS_SgkIseGiris, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class WS_SgkIseGirisClient : System.ServiceModel.ClientBase<SgkIseGirisServiceReference.WS_SgkIseGiris>, SgkIseGirisServiceReference.WS_SgkIseGiris
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WS_SgkIseGirisClient() : 
                base(WS_SgkIseGirisClient.GetDefaultBinding(), WS_SgkIseGirisClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.WS_SgkIseGirisPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WS_SgkIseGirisClient(EndpointConfiguration endpointConfiguration) : 
                base(WS_SgkIseGirisClient.GetBindingForEndpoint(endpointConfiguration), WS_SgkIseGirisClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WS_SgkIseGirisClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WS_SgkIseGirisClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WS_SgkIseGirisClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WS_SgkIseGirisClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WS_SgkIseGirisClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SgkIseGirisServiceReference.iseGirisKaydetResponse> SgkIseGirisServiceReference.WS_SgkIseGiris.iseGirisKaydetAsync(SgkIseGirisServiceReference.iseGirisKaydetRequest request)
        {
            return base.Channel.iseGirisKaydetAsync(request);
        }
        
        public System.Threading.Tasks.Task<SgkIseGirisServiceReference.iseGirisKaydetResponse> iseGirisKaydetAsync(SgkIseGirisServiceReference.sgk4AIseGirisParametre sgk4aIseGirisParametre)
        {
            SgkIseGirisServiceReference.iseGirisKaydetRequest inValue = new SgkIseGirisServiceReference.iseGirisKaydetRequest();
            inValue.sgk4aIseGirisParametre = sgk4aIseGirisParametre;
            return ((SgkIseGirisServiceReference.WS_SgkIseGiris)(this)).iseGirisKaydetAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SgkIseGirisServiceReference.iseGirisPdfDokumResponse> SgkIseGirisServiceReference.WS_SgkIseGiris.iseGirisPdfDokumAsync(SgkIseGirisServiceReference.iseGirisPdfDokumRequest request)
        {
            return base.Channel.iseGirisPdfDokumAsync(request);
        }
        
        public System.Threading.Tasks.Task<SgkIseGirisServiceReference.iseGirisPdfDokumResponse> iseGirisPdfDokumAsync(SgkIseGirisServiceReference.kullaniciBilgileri kullanici, long referansKodu)
        {
            SgkIseGirisServiceReference.iseGirisPdfDokumRequest inValue = new SgkIseGirisServiceReference.iseGirisPdfDokumRequest();
            inValue.kullanici = kullanici;
            inValue.referansKodu = referansKodu;
            return ((SgkIseGirisServiceReference.WS_SgkIseGiris)(this)).iseGirisPdfDokumAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SgkIseGirisServiceReference.tckimlikNoileiseGirisSorgulaResponse> SgkIseGirisServiceReference.WS_SgkIseGiris.tckimlikNoileiseGirisSorgulaAsync(SgkIseGirisServiceReference.tckimlikNoileiseGirisSorgulaRequest request)
        {
            return base.Channel.tckimlikNoileiseGirisSorgulaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SgkIseGirisServiceReference.tckimlikNoileiseGirisSorgulaResponse> tckimlikNoileiseGirisSorgulaAsync(SgkIseGirisServiceReference.tcKimliktenIseGirisSorParametre tcKimliktenIseGirisSorParametre)
        {
            SgkIseGirisServiceReference.tckimlikNoileiseGirisSorgulaRequest inValue = new SgkIseGirisServiceReference.tckimlikNoileiseGirisSorgulaRequest();
            inValue.tcKimliktenIseGirisSorParametre = tcKimliktenIseGirisSorParametre;
            return ((SgkIseGirisServiceReference.WS_SgkIseGiris)(this)).tckimlikNoileiseGirisSorgulaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SgkIseGirisServiceReference.tckimlikNoTarihileiseGirisSorgulaResponse> SgkIseGirisServiceReference.WS_SgkIseGiris.tckimlikNoTarihileiseGirisSorgulaAsync(SgkIseGirisServiceReference.tckimlikNoTarihileiseGirisSorgulaRequest request)
        {
            return base.Channel.tckimlikNoTarihileiseGirisSorgulaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SgkIseGirisServiceReference.tckimlikNoTarihileiseGirisSorgulaResponse> tckimlikNoTarihileiseGirisSorgulaAsync(SgkIseGirisServiceReference.tcKimlikTarihtenIseGirisSorParametre tcKimlikTarihtenIseGirisSorParametre)
        {
            SgkIseGirisServiceReference.tckimlikNoTarihileiseGirisSorgulaRequest inValue = new SgkIseGirisServiceReference.tckimlikNoTarihileiseGirisSorgulaRequest();
            inValue.tcKimlikTarihtenIseGirisSorParametre = tcKimlikTarihtenIseGirisSorParametre;
            return ((SgkIseGirisServiceReference.WS_SgkIseGiris)(this)).tckimlikNoTarihileiseGirisSorgulaAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WS_SgkIseGirisPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WS_SgkIseGirisPort))
            {
                return new System.ServiceModel.EndpointAddress("https://sgkt.sgk.gov.tr/WS_SgkTescil4a/WS_SgkIseGirisService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return WS_SgkIseGirisClient.GetBindingForEndpoint(EndpointConfiguration.WS_SgkIseGirisPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return WS_SgkIseGirisClient.GetEndpointAddress(EndpointConfiguration.WS_SgkIseGirisPort);
        }
        
        public enum EndpointConfiguration
        {
            
            WS_SgkIseGirisPort,
        }
    }
}
