//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SgkIstenCikisServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr", ConfigurationName="SgkIstenCikisServiceReference.WS_SgkIstenCikis")]
    public interface WS_SgkIstenCikis
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="istenCikisDonemVeGunSayisiBul", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SgkIstenCikisServiceReference.istenCikisDonemVeGunSayisiBulResponse> istenCikisDonemVeGunSayisiBulAsync(SgkIstenCikisServiceReference.istenCikisDonemVeGunSayisiBulRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="istenCikisKaydet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SgkIstenCikisServiceReference.istenCikisKaydetResponse> istenCikisKaydetAsync(SgkIstenCikisServiceReference.istenCikisKaydetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="istenCikisPdfDokum", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SgkIstenCikisServiceReference.istenCikisPdfDokumResponse> istenCikisPdfDokumAsync(SgkIstenCikisServiceReference.istenCikisPdfDokumRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="tckimlikNoileistenCikisSorgula", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SgkIstenCikisServiceReference.tckimlikNoileistenCikisSorgulaResponse> tckimlikNoileistenCikisSorgulaAsync(SgkIstenCikisServiceReference.tckimlikNoileistenCikisSorgulaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="tckimlikNoTarihileistenCikisSorgula", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SgkIstenCikisServiceReference.tckimlikNoTarihileistenCikisSorgulaResponse> tckimlikNoTarihileistenCikisSorgulaAsync(SgkIstenCikisServiceReference.tckimlikNoTarihileistenCikisSorgulaRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr")]
    public partial class kullaniciBilgileri
    {
        
        private string kullaniciAdiField;
        
        private string isyeriKoduField;
        
        private string sistemSifreField;
        
        private string isyeriSifreField;
        
        private string isyeriSicilField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string kullaniciAdi
        {
            get
            {
                return this.kullaniciAdiField;
            }
            set
            {
                this.kullaniciAdiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string isyeriKodu
        {
            get
            {
                return this.isyeriKoduField;
            }
            set
            {
                this.isyeriKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string sistemSifre
        {
            get
            {
                return this.sistemSifreField;
            }
            set
            {
                this.sistemSifreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string isyeriSifre
        {
            get
            {
                return this.isyeriSifreField;
            }
            set
            {
                this.isyeriSifreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string isyeriSicil
        {
            get
            {
                return this.isyeriSicilField;
            }
            set
            {
                this.isyeriSicilField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr")]
    public partial class tcKimlikTarihtenIstenCikisSorParametre
    {
        
        private kullaniciBilgileri kullaniciBilgileriField;
        
        private long tcKimlikNoField;
        
        private string istenCikisTarihiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public kullaniciBilgileri kullaniciBilgileri
        {
            get
            {
                return this.kullaniciBilgileriField;
            }
            set
            {
                this.kullaniciBilgileriField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long tcKimlikNo
        {
            get
            {
                return this.tcKimlikNoField;
            }
            set
            {
                this.tcKimlikNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string istenCikisTarihi
        {
            get
            {
                return this.istenCikisTarihiField;
            }
            set
            {
                this.istenCikisTarihiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr")]
    public partial class sgkIstenCikisKaydi
    {
        
        private long tckimlikNoField;
        
        private long sicilnoField;
        
        private string cikisTarihiField;
        
        private string islemTarihiField;
        
        private double idariParaCezasiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long tckimlikNo
        {
            get
            {
                return this.tckimlikNoField;
            }
            set
            {
                this.tckimlikNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long sicilno
        {
            get
            {
                return this.sicilnoField;
            }
            set
            {
                this.sicilnoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string cikisTarihi
        {
            get
            {
                return this.cikisTarihiField;
            }
            set
            {
                this.cikisTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string islemTarihi
        {
            get
            {
                return this.islemTarihiField;
            }
            set
            {
                this.islemTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double idariParaCezasi
        {
            get
            {
                return this.idariParaCezasiField;
            }
            set
            {
                this.idariParaCezasiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr")]
    public partial class istenCikisListesi
    {
        
        private int hatakoduField;
        
        private string hataAciklamaField;
        
        private sgkIstenCikisKaydi[] istenCikisKayitlariField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int hatakodu
        {
            get
            {
                return this.hatakoduField;
            }
            set
            {
                this.hatakoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string hataAciklama
        {
            get
            {
                return this.hataAciklamaField;
            }
            set
            {
                this.hataAciklamaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("istenCikisKayitlari", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public sgkIstenCikisKaydi[] istenCikisKayitlari
        {
            get
            {
                return this.istenCikisKayitlariField;
            }
            set
            {
                this.istenCikisKayitlariField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr")]
    public partial class tcKimliktenIstenCikisSorParametre
    {
        
        private kullaniciBilgileri kullaniciBilgileriField;
        
        private long tcKimlikNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public kullaniciBilgileri kullaniciBilgileri
        {
            get
            {
                return this.kullaniciBilgileriField;
            }
            set
            {
                this.kullaniciBilgileriField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long tcKimlikNo
        {
            get
            {
                return this.tcKimlikNoField;
            }
            set
            {
                this.tcKimlikNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr")]
    public partial class pdfDokumSonuc
    {
        
        private string hataAciklamaField;
        
        private int hatakoduField;
        
        private byte[] pdfByteArrayField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string hataAciklama
        {
            get
            {
                return this.hataAciklamaField;
            }
            set
            {
                this.hataAciklamaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int hatakodu
        {
            get
            {
                return this.hatakoduField;
            }
            set
            {
                this.hatakoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=2)]
        public byte[] pdfByteArray
        {
            get
            {
                return this.pdfByteArrayField;
            }
            set
            {
                this.pdfByteArrayField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr")]
    public partial class sigortaliIstenCikisSonuc
    {
        
        private long islemSonucuField;
        
        private string islemAciklamasiField;
        
        private long tcKimlikNoField;
        
        private string sicilnoField;
        
        private string adSoyadField;
        
        private long referansKoduField;
        
        private string istenCikisTarihiField;
        
        private string isyeriSicilField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long islemSonucu
        {
            get
            {
                return this.islemSonucuField;
            }
            set
            {
                this.islemSonucuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string islemAciklamasi
        {
            get
            {
                return this.islemAciklamasiField;
            }
            set
            {
                this.islemAciklamasiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long tcKimlikNo
        {
            get
            {
                return this.tcKimlikNoField;
            }
            set
            {
                this.tcKimlikNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string sicilno
        {
            get
            {
                return this.sicilnoField;
            }
            set
            {
                this.sicilnoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string adSoyad
        {
            get
            {
                return this.adSoyadField;
            }
            set
            {
                this.adSoyadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public long referansKodu
        {
            get
            {
                return this.referansKoduField;
            }
            set
            {
                this.referansKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string istenCikisTarihi
        {
            get
            {
                return this.istenCikisTarihiField;
            }
            set
            {
                this.istenCikisTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string isyeriSicil
        {
            get
            {
                return this.isyeriSicilField;
            }
            set
            {
                this.isyeriSicilField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr")]
    public partial class sigortaliIstenCikisIslemSonuclari
    {
        
        private int hataKoduField;
        
        private string hataAciklamasiField;
        
        private sigortaliIstenCikisSonuc[] sigortaliIstenCikisSonucField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int hataKodu
        {
            get
            {
                return this.hataKoduField;
            }
            set
            {
                this.hataKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string hataAciklamasi
        {
            get
            {
                return this.hataAciklamasiField;
            }
            set
            {
                this.hataAciklamasiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sigortaliIstenCikisSonuc", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public sigortaliIstenCikisSonuc[] sigortaliIstenCikisSonuc
        {
            get
            {
                return this.sigortaliIstenCikisSonucField;
            }
            set
            {
                this.sigortaliIstenCikisSonucField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr")]
    public partial class oncekiDonem
    {
        
        private short belgeturuField;
        
        private double hakedilenucretField;
        
        private double primikramiyeField;
        
        private short eksikgunsayisiField;
        
        private short eksikgunnedeniField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public short belgeturu
        {
            get
            {
                return this.belgeturuField;
            }
            set
            {
                this.belgeturuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double hakedilenucret
        {
            get
            {
                return this.hakedilenucretField;
            }
            set
            {
                this.hakedilenucretField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double primikramiye
        {
            get
            {
                return this.primikramiyeField;
            }
            set
            {
                this.primikramiyeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public short eksikgunsayisi
        {
            get
            {
                return this.eksikgunsayisiField;
            }
            set
            {
                this.eksikgunsayisiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public short eksikgunnedeni
        {
            get
            {
                return this.eksikgunnedeniField;
            }
            set
            {
                this.eksikgunnedeniField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr")]
    public partial class bulundugumuzDonem
    {
        
        private short belgeturuField;
        
        private double hakedilenucretField;
        
        private double primikramiyeField;
        
        private short eksikgunsayisiField;
        
        private short eksikgunnedeniField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public short belgeturu
        {
            get
            {
                return this.belgeturuField;
            }
            set
            {
                this.belgeturuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double hakedilenucret
        {
            get
            {
                return this.hakedilenucretField;
            }
            set
            {
                this.hakedilenucretField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double primikramiye
        {
            get
            {
                return this.primikramiyeField;
            }
            set
            {
                this.primikramiyeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public short eksikgunsayisi
        {
            get
            {
                return this.eksikgunsayisiField;
            }
            set
            {
                this.eksikgunsayisiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public short eksikgunnedeni
        {
            get
            {
                return this.eksikgunnedeniField;
            }
            set
            {
                this.eksikgunnedeniField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr")]
    public partial class sigortaliIstenCikis
    {
        
        private long tckimlikNoField;
        
        private string adField;
        
        private string soyadField;
        
        private string istenCikisTarihiField;
        
        private string istenCikisNedeniField;
        
        private string meslekkoduField;
        
        private string csgbiskoluField;
        
        private bulundugumuzDonem bulundugumuzDonemField;
        
        private oncekiDonem oncekiDonemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long tckimlikNo
        {
            get
            {
                return this.tckimlikNoField;
            }
            set
            {
                this.tckimlikNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ad
        {
            get
            {
                return this.adField;
            }
            set
            {
                this.adField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string soyad
        {
            get
            {
                return this.soyadField;
            }
            set
            {
                this.soyadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string istenCikisTarihi
        {
            get
            {
                return this.istenCikisTarihiField;
            }
            set
            {
                this.istenCikisTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string istenCikisNedeni
        {
            get
            {
                return this.istenCikisNedeniField;
            }
            set
            {
                this.istenCikisNedeniField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string meslekkodu
        {
            get
            {
                return this.meslekkoduField;
            }
            set
            {
                this.meslekkoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string csgbiskolu
        {
            get
            {
                return this.csgbiskoluField;
            }
            set
            {
                this.csgbiskoluField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public bulundugumuzDonem bulundugumuzDonem
        {
            get
            {
                return this.bulundugumuzDonemField;
            }
            set
            {
                this.bulundugumuzDonemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public oncekiDonem oncekiDonem
        {
            get
            {
                return this.oncekiDonemField;
            }
            set
            {
                this.oncekiDonemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr")]
    public partial class sgk4AIstenCikisParametre
    {
        
        private kullaniciBilgileri kullaniciBilgileriField;
        
        private sigortaliIstenCikis[] sigortaliIstenCikisListesiField;
        
        private string nakilGidecegiIsyeriSicilField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public kullaniciBilgileri kullaniciBilgileri
        {
            get
            {
                return this.kullaniciBilgileriField;
            }
            set
            {
                this.kullaniciBilgileriField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sigortaliIstenCikisListesi", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public sigortaliIstenCikis[] sigortaliIstenCikisListesi
        {
            get
            {
                return this.sigortaliIstenCikisListesiField;
            }
            set
            {
                this.sigortaliIstenCikisListesiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nakilGidecegiIsyeriSicil
        {
            get
            {
                return this.nakilGidecegiIsyeriSicilField;
            }
            set
            {
                this.nakilGidecegiIsyeriSicilField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr")]
    public partial class istenCikisDonemBilgileri
    {
        
        private long tckimlikNoField;
        
        private int islemSonucuField;
        
        private string islemSonucAciklamasiField;
        
        private string istenCikisTarihiField;
        
        private string iseGirisTarihiField;
        
        private string bulundugumuzDonemBaslangicTarihiField;
        
        private string bulundugumuzDonemBitisTarihiField;
        
        private int bulundugumuzDonemGunSayisiField;
        
        private string oncekiDonemBaslangicTarihiField;
        
        private string oncekiDonemBitisTarihiField;
        
        private int oncekiDonemGunSayisiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long tckimlikNo
        {
            get
            {
                return this.tckimlikNoField;
            }
            set
            {
                this.tckimlikNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int islemSonucu
        {
            get
            {
                return this.islemSonucuField;
            }
            set
            {
                this.islemSonucuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string islemSonucAciklamasi
        {
            get
            {
                return this.islemSonucAciklamasiField;
            }
            set
            {
                this.islemSonucAciklamasiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string istenCikisTarihi
        {
            get
            {
                return this.istenCikisTarihiField;
            }
            set
            {
                this.istenCikisTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string iseGirisTarihi
        {
            get
            {
                return this.iseGirisTarihiField;
            }
            set
            {
                this.iseGirisTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string bulundugumuzDonemBaslangicTarihi
        {
            get
            {
                return this.bulundugumuzDonemBaslangicTarihiField;
            }
            set
            {
                this.bulundugumuzDonemBaslangicTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string bulundugumuzDonemBitisTarihi
        {
            get
            {
                return this.bulundugumuzDonemBitisTarihiField;
            }
            set
            {
                this.bulundugumuzDonemBitisTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int bulundugumuzDonemGunSayisi
        {
            get
            {
                return this.bulundugumuzDonemGunSayisiField;
            }
            set
            {
                this.bulundugumuzDonemGunSayisiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string oncekiDonemBaslangicTarihi
        {
            get
            {
                return this.oncekiDonemBaslangicTarihiField;
            }
            set
            {
                this.oncekiDonemBaslangicTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string oncekiDonemBitisTarihi
        {
            get
            {
                return this.oncekiDonemBitisTarihiField;
            }
            set
            {
                this.oncekiDonemBitisTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public int oncekiDonemGunSayisi
        {
            get
            {
                return this.oncekiDonemGunSayisiField;
            }
            set
            {
                this.oncekiDonemGunSayisiField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="istenCikisDonemVeGunSayisiBul", WrapperNamespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr", IsWrapped=true)]
    public partial class istenCikisDonemVeGunSayisiBulRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SgkIstenCikisServiceReference.kullaniciBilgileri kullanici;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long tckimlikno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string istenCikisTarihi;
        
        public istenCikisDonemVeGunSayisiBulRequest()
        {
        }
        
        public istenCikisDonemVeGunSayisiBulRequest(SgkIstenCikisServiceReference.kullaniciBilgileri kullanici, long tckimlikno, string istenCikisTarihi)
        {
            this.kullanici = kullanici;
            this.tckimlikno = tckimlikno;
            this.istenCikisTarihi = istenCikisTarihi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="istenCikisDonemVeGunSayisiBulResponse", WrapperNamespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr", IsWrapped=true)]
    public partial class istenCikisDonemVeGunSayisiBulResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SgkIstenCikisServiceReference.istenCikisDonemBilgileri istenCikisDonemVeGunSayisiBulReturn;
        
        public istenCikisDonemVeGunSayisiBulResponse()
        {
        }
        
        public istenCikisDonemVeGunSayisiBulResponse(SgkIstenCikisServiceReference.istenCikisDonemBilgileri istenCikisDonemVeGunSayisiBulReturn)
        {
            this.istenCikisDonemVeGunSayisiBulReturn = istenCikisDonemVeGunSayisiBulReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="istenCikisKaydet", WrapperNamespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr", IsWrapped=true)]
    public partial class istenCikisKaydetRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SgkIstenCikisServiceReference.sgk4AIstenCikisParametre sgk4aIstenCikisParametre;
        
        public istenCikisKaydetRequest()
        {
        }
        
        public istenCikisKaydetRequest(SgkIstenCikisServiceReference.sgk4AIstenCikisParametre sgk4aIstenCikisParametre)
        {
            this.sgk4aIstenCikisParametre = sgk4aIstenCikisParametre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="istenCikisKaydetResponse", WrapperNamespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr", IsWrapped=true)]
    public partial class istenCikisKaydetResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SgkIstenCikisServiceReference.sigortaliIstenCikisIslemSonuclari istenCikisKaydetReturn;
        
        public istenCikisKaydetResponse()
        {
        }
        
        public istenCikisKaydetResponse(SgkIstenCikisServiceReference.sigortaliIstenCikisIslemSonuclari istenCikisKaydetReturn)
        {
            this.istenCikisKaydetReturn = istenCikisKaydetReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="istenCikisPdfDokum", WrapperNamespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr", IsWrapped=true)]
    public partial class istenCikisPdfDokumRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SgkIstenCikisServiceReference.kullaniciBilgileri kullanici;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long referansKodu;
        
        public istenCikisPdfDokumRequest()
        {
        }
        
        public istenCikisPdfDokumRequest(SgkIstenCikisServiceReference.kullaniciBilgileri kullanici, long referansKodu)
        {
            this.kullanici = kullanici;
            this.referansKodu = referansKodu;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="istenCikisPdfDokumResponse", WrapperNamespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr", IsWrapped=true)]
    public partial class istenCikisPdfDokumResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SgkIstenCikisServiceReference.pdfDokumSonuc istenCikisPdfDokumReturn;
        
        public istenCikisPdfDokumResponse()
        {
        }
        
        public istenCikisPdfDokumResponse(SgkIstenCikisServiceReference.pdfDokumSonuc istenCikisPdfDokumReturn)
        {
            this.istenCikisPdfDokumReturn = istenCikisPdfDokumReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="tckimlikNoileistenCikisSorgula", WrapperNamespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr", IsWrapped=true)]
    public partial class tckimlikNoileistenCikisSorgulaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SgkIstenCikisServiceReference.tcKimliktenIstenCikisSorParametre tcKimliktenIstenCikisSorParametre;
        
        public tckimlikNoileistenCikisSorgulaRequest()
        {
        }
        
        public tckimlikNoileistenCikisSorgulaRequest(SgkIstenCikisServiceReference.tcKimliktenIstenCikisSorParametre tcKimliktenIstenCikisSorParametre)
        {
            this.tcKimliktenIstenCikisSorParametre = tcKimliktenIstenCikisSorParametre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="tckimlikNoileistenCikisSorgulaResponse", WrapperNamespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr", IsWrapped=true)]
    public partial class tckimlikNoileistenCikisSorgulaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SgkIstenCikisServiceReference.istenCikisListesi tckimlikNoileistenCikisSorgulaReturn;
        
        public tckimlikNoileistenCikisSorgulaResponse()
        {
        }
        
        public tckimlikNoileistenCikisSorgulaResponse(SgkIstenCikisServiceReference.istenCikisListesi tckimlikNoileistenCikisSorgulaReturn)
        {
            this.tckimlikNoileistenCikisSorgulaReturn = tckimlikNoileistenCikisSorgulaReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="tckimlikNoTarihileistenCikisSorgula", WrapperNamespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr", IsWrapped=true)]
    public partial class tckimlikNoTarihileistenCikisSorgulaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SgkIstenCikisServiceReference.tcKimlikTarihtenIstenCikisSorParametre tcKimlikTarihtenIstenCikisSorParametre;
        
        public tckimlikNoTarihileistenCikisSorgulaRequest()
        {
        }
        
        public tckimlikNoTarihileistenCikisSorgulaRequest(SgkIstenCikisServiceReference.tcKimlikTarihtenIstenCikisSorParametre tcKimlikTarihtenIstenCikisSorParametre)
        {
            this.tcKimlikTarihtenIstenCikisSorParametre = tcKimlikTarihtenIstenCikisSorParametre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="tckimlikNoTarihileistenCikisSorgulaResponse", WrapperNamespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr", IsWrapped=true)]
    public partial class tckimlikNoTarihileistenCikisSorgulaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SgkIstenCikisServiceReference.istenCikisListesi tckimlikNoTarihileistenCikisSorgulaReturn;
        
        public tckimlikNoTarihileistenCikisSorgulaResponse()
        {
        }
        
        public tckimlikNoTarihileistenCikisSorgulaResponse(SgkIstenCikisServiceReference.istenCikisListesi tckimlikNoTarihileistenCikisSorgulaReturn)
        {
            this.tckimlikNoTarihileistenCikisSorgulaReturn = tckimlikNoTarihileistenCikisSorgulaReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface WS_SgkIstenCikisChannel : SgkIstenCikisServiceReference.WS_SgkIstenCikis, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class WS_SgkIstenCikisClient : System.ServiceModel.ClientBase<SgkIstenCikisServiceReference.WS_SgkIstenCikis>, SgkIstenCikisServiceReference.WS_SgkIstenCikis
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WS_SgkIstenCikisClient() : 
                base(WS_SgkIstenCikisClient.GetDefaultBinding(), WS_SgkIstenCikisClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.WS_SgkIstenCikisPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WS_SgkIstenCikisClient(EndpointConfiguration endpointConfiguration) : 
                base(WS_SgkIstenCikisClient.GetBindingForEndpoint(endpointConfiguration), WS_SgkIstenCikisClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WS_SgkIstenCikisClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WS_SgkIstenCikisClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WS_SgkIstenCikisClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WS_SgkIstenCikisClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WS_SgkIstenCikisClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SgkIstenCikisServiceReference.istenCikisDonemVeGunSayisiBulResponse> SgkIstenCikisServiceReference.WS_SgkIstenCikis.istenCikisDonemVeGunSayisiBulAsync(SgkIstenCikisServiceReference.istenCikisDonemVeGunSayisiBulRequest request)
        {
            return base.Channel.istenCikisDonemVeGunSayisiBulAsync(request);
        }
        
        public System.Threading.Tasks.Task<SgkIstenCikisServiceReference.istenCikisDonemVeGunSayisiBulResponse> istenCikisDonemVeGunSayisiBulAsync(SgkIstenCikisServiceReference.kullaniciBilgileri kullanici, long tckimlikno, string istenCikisTarihi)
        {
            SgkIstenCikisServiceReference.istenCikisDonemVeGunSayisiBulRequest inValue = new SgkIstenCikisServiceReference.istenCikisDonemVeGunSayisiBulRequest();
            inValue.kullanici = kullanici;
            inValue.tckimlikno = tckimlikno;
            inValue.istenCikisTarihi = istenCikisTarihi;
            return ((SgkIstenCikisServiceReference.WS_SgkIstenCikis)(this)).istenCikisDonemVeGunSayisiBulAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SgkIstenCikisServiceReference.istenCikisKaydetResponse> SgkIstenCikisServiceReference.WS_SgkIstenCikis.istenCikisKaydetAsync(SgkIstenCikisServiceReference.istenCikisKaydetRequest request)
        {
            return base.Channel.istenCikisKaydetAsync(request);
        }
        
        public System.Threading.Tasks.Task<SgkIstenCikisServiceReference.istenCikisKaydetResponse> istenCikisKaydetAsync(SgkIstenCikisServiceReference.sgk4AIstenCikisParametre sgk4aIstenCikisParametre)
        {
            SgkIstenCikisServiceReference.istenCikisKaydetRequest inValue = new SgkIstenCikisServiceReference.istenCikisKaydetRequest();
            inValue.sgk4aIstenCikisParametre = sgk4aIstenCikisParametre;
            return ((SgkIstenCikisServiceReference.WS_SgkIstenCikis)(this)).istenCikisKaydetAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SgkIstenCikisServiceReference.istenCikisPdfDokumResponse> SgkIstenCikisServiceReference.WS_SgkIstenCikis.istenCikisPdfDokumAsync(SgkIstenCikisServiceReference.istenCikisPdfDokumRequest request)
        {
            return base.Channel.istenCikisPdfDokumAsync(request);
        }
        
        public System.Threading.Tasks.Task<SgkIstenCikisServiceReference.istenCikisPdfDokumResponse> istenCikisPdfDokumAsync(SgkIstenCikisServiceReference.kullaniciBilgileri kullanici, long referansKodu)
        {
            SgkIstenCikisServiceReference.istenCikisPdfDokumRequest inValue = new SgkIstenCikisServiceReference.istenCikisPdfDokumRequest();
            inValue.kullanici = kullanici;
            inValue.referansKodu = referansKodu;
            return ((SgkIstenCikisServiceReference.WS_SgkIstenCikis)(this)).istenCikisPdfDokumAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SgkIstenCikisServiceReference.tckimlikNoileistenCikisSorgulaResponse> SgkIstenCikisServiceReference.WS_SgkIstenCikis.tckimlikNoileistenCikisSorgulaAsync(SgkIstenCikisServiceReference.tckimlikNoileistenCikisSorgulaRequest request)
        {
            return base.Channel.tckimlikNoileistenCikisSorgulaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SgkIstenCikisServiceReference.tckimlikNoileistenCikisSorgulaResponse> tckimlikNoileistenCikisSorgulaAsync(SgkIstenCikisServiceReference.tcKimliktenIstenCikisSorParametre tcKimliktenIstenCikisSorParametre)
        {
            SgkIstenCikisServiceReference.tckimlikNoileistenCikisSorgulaRequest inValue = new SgkIstenCikisServiceReference.tckimlikNoileistenCikisSorgulaRequest();
            inValue.tcKimliktenIstenCikisSorParametre = tcKimliktenIstenCikisSorParametre;
            return ((SgkIstenCikisServiceReference.WS_SgkIstenCikis)(this)).tckimlikNoileistenCikisSorgulaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SgkIstenCikisServiceReference.tckimlikNoTarihileistenCikisSorgulaResponse> SgkIstenCikisServiceReference.WS_SgkIstenCikis.tckimlikNoTarihileistenCikisSorgulaAsync(SgkIstenCikisServiceReference.tckimlikNoTarihileistenCikisSorgulaRequest request)
        {
            return base.Channel.tckimlikNoTarihileistenCikisSorgulaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SgkIstenCikisServiceReference.tckimlikNoTarihileistenCikisSorgulaResponse> tckimlikNoTarihileistenCikisSorgulaAsync(SgkIstenCikisServiceReference.tcKimlikTarihtenIstenCikisSorParametre tcKimlikTarihtenIstenCikisSorParametre)
        {
            SgkIstenCikisServiceReference.tckimlikNoTarihileistenCikisSorgulaRequest inValue = new SgkIstenCikisServiceReference.tckimlikNoTarihileistenCikisSorgulaRequest();
            inValue.tcKimlikTarihtenIstenCikisSorParametre = tcKimlikTarihtenIstenCikisSorParametre;
            return ((SgkIstenCikisServiceReference.WS_SgkIstenCikis)(this)).tckimlikNoTarihileistenCikisSorgulaAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WS_SgkIstenCikisPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WS_SgkIstenCikisPort))
            {
                return new System.ServiceModel.EndpointAddress("https://sgkt.sgk.gov.tr/WS_SgkTescil4a/WS_SgkIstenCikisService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return WS_SgkIstenCikisClient.GetBindingForEndpoint(EndpointConfiguration.WS_SgkIstenCikisPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return WS_SgkIstenCikisClient.GetEndpointAddress(EndpointConfiguration.WS_SgkIstenCikisPort);
        }
        
        public enum EndpointConfiguration
        {
            
            WS_SgkIstenCikisPort,
        }
    }
}
